# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: required

services:
  - docker

language: go

# Only clone the most recent commit.
git:
  depth: 1

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - env GO111MODULE=on go build
  - go GO111MODULE=on test ./...